---
collections:
#  - name: community.general
#    version: 6.5.0
#    source: https://galaxy.ansible.com

  - name: servicenow.itsm
    version: 2.3.0

  - name: community.zabbix
    version: 2.3.1
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0    
