---
- name: Handle zabbix alert
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Handle zabbix alert
      #condition: event.payload is defined
      #condition: event.payload.event_nseverity >= 2
      #警告以上 AND ディスク容量の枯渇
      condition: 
        any:
          - event.payload.event_nseverity >= 2
          - event.payload.trigger_id == "23249"
      action:
        run_job_template:
          name: 'Server Group Assessment'
          organization: Default

#Playbookに対するextra_varsなどによる明示的なパラメーター渡しは機能しないようだ
#'variables_needed_to_start': ["'zabbix_host_group' value missing"]で弾かれる
#DefaultでPayloadが丸ごとPlaybookのパラメータとして渡されるので、それを使用する
#          extra_vars:
#            zabbix_host_group: "aiueo"
    