---
- name: Handle zabbix alert
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Handle zabbix alert
      #condition: event.payload is defined
      condition: event.payload.nseverity >= 2 and trigger_name = "/: Disk space is low" #警告以上
      action:
        run_job_template:
          name: 'Server Group Assessment'
          organization: Default

#Playbookに対するextra_varsなどによる明示的なパラメーター渡しは機能しないようだ
#'variables_needed_to_start': ["'zabbix_host_group' value missing"]で弾かれる
#DefaultでPayloadが丸ごとPlaybookのパラメータとして渡されるので、それを使用する
#          extra_vars:
#            zabbix_host_group: "aiueo"
    