---
- name: Handle Zabbix event
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Disk High Usage Action
      #condition: event.payload.trigger_id == 23284
      condition: event.payload.trigger_name is search("Disk space is critically low", ignorecase=true)
      action:
        run_job_template:
          name: 'Disk High Usage Action'
          organization: Default
        debug:
         msg: "Received: {{ event.payload }}"

#    - name: xxx Action
#      condition: event.payload.trigger_id == xxxxx
#      action:
#        run_job_template:
#          name: 'xxxxx'
#          organization: Default         
