---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello test
      condition: event.payload is defined
      action:
        run_job_template:
          name: 'Demo Job Template'
          organization: Default
        debug:
         msg: "Received: {{ event.payload }}"         