---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello test
      condition: trigger_id == 23284
      action:
        run_job_template:
          name: 'Server Group Assessment'
          organization: Default
        debug:
         msg: "Received: {{ event.payload }}"         