---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Handle trigger 232841 'Disk space is critically low'
      condition: event.payload.trigger_id == 232841
      action:
        run_job_template:
          name: 'Server Group Assessment'
          organization: Default
        debug:
         msg: "Received: {{ event.payload }}"         