---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello test
      condition: event.payload is defined
      action:
        run_job_template:
          name: 'Server Group Assessment'
          organization: Default
          extra_vars:
            host_ip: "{{ event.payload.host_ip }}"
        debug:
         msg: "Received: {{ event.payload.host_groups }}"         