---
- name: Execute df command on hosts from Zabbix host group
  #hosts: localhost
  hosts: all
  gather_facts: no

  vars:
    target_ip: "{{ ansible_eda.event.payload.host_ip | default('NA') }}"
    host_groups: "{{ ansible_eda.event.payload.host_groups | default('NA') }}"

  tasks:
    - name: Show vars
      debug:
        msg: "{{target_ip}} {{host_groups}} {{ansible_groups}}"      

    - name: Checking high-usage directories
      #ansible.builtin.command: 
      block:
        - name: Checking high-usage directories
          ansible.builtin.shell: 
            cmd: df -h --output=target,pcent
          register: disk_usage

        - name: Checking high-usage directories
          ansible.builtin.shell: 
            cmd: sudo du -ahx / | sort -rh | head -n 10
          register: disk_usage_top10

        - name: Show the result
          ansible.builtin.debug:
            msg: "{{ disk_usage.stdout_lines }}"

        - name: Show the result2
          ansible.builtin.debug:
            msg: "{{ disk_usage_top10.stdout_lines }}"

      when: (ansible_groups | intersect(host_groups) | length) > 0

