---
- name: Execute df command on hosts from Zabbix host group
  #hosts: localhost
  hosts: all
  gather_facts: no

  vars:
    host_group: "{{ ansible_eda.event.payload.host_groups | default('blank') }}"
    target_ip: "{{ ansible_eda.event.payload.host_ip | default('NA') }}"

  tasks:
    - name: Show df command output
      debug:
        msg: "{{ host_group }}{{ target_ip }}"      

    - name: Check if the host matches the specific IP address
      #ansible.builtin.command: 
      ansible.builtin.shell: 
        #cmd: du -a / | sort -n -r | head -n 5
        cmd: sudo du -ahx / | sort -rh | head -n 10
      register: disk_usage
      when: ansible_host == target_ip

    - name: Show the result
      ansible.builtin.debug:
        msg: "{{ disk_usage.stdout_lines }}"
      when: ansible_host == target_ip