---
- name: Execute df command on hosts from Zabbix host group
  hosts: localhost
  gather_facts: no

  vars:
    host_group: "{{ ansible_eda.event.payload.host_groups | default('blank') }}"

  tasks:
    - name: Show df command output
      debug:
        msg: "{{ host_group }}"
